default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  # Commit Message Standards
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose]

  # General File Hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
 #     - id: no-commit-to-branch (Commented to be able to commit to main directly)
 #       args: [--branch, main] # Protects the main branch

  # Security (Secret Scanning)
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.1
    hooks:
      - id: gitleaks

  # Python Specific
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  # Spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["-L", "te,nd"]
